trigger:
  tags:
    include:
      - 'FW_v*.*.*'

pr: none

variables:
  MSP430_GCC_VERSION: 9.3.1.11
  MSP430_SUPPORT_VERSION: 1.212

jobs:
  - job: Build
    displayName: Build MSP430 Firmware
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self

      - bash: |
          mkdir -p ~/msp430-gcc
          tar -xf sfw-00082/gcc/toolchain/msp430-gcc-$(MSP430_GCC_VERSION)_linux64.tar.bz2 --strip-components=1 -C ~/msp430-gcc
        displayName: Install MSP430-GCC compiler

      - bash: |
          unzip -q sfw-00082/gcc/toolchain/msp430-gcc-support-files-$(MSP430_SUPPORT_VERSION).zip -d ~
        displayName: Install MSP430-GCC support files

      - bash: |
          echo "##vso[task.prependpath]$HOME/msp430-gcc/bin"
        displayName: Add toolchain to PATH

      - bash: make -C sfw-00082/gcc SUPPORT_FILE_DIR=$HOME/msp430-gcc-support-files/include
        displayName: Build firmware

      - task: CopyFiles@2
        displayName: Stage firmware artifacts
        inputs:
          sourceFolder: sfw-00082/gcc/gcc-build
          contents: |
            sfw-00082.elf
            sfw-00082.hex
          targetFolder: $(Build.ArtifactStagingDirectory)/firmware

      - task: PublishPipelineArtifact@1
        displayName: Upload firmware artifacts
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)/firmware
          artifact: firmware
          publishLocation: pipeline
