trigger:
  tags:
    include:
      - 'Test_App_v*.*.*.*'

pr: none

jobs:
  - job: Release
    displayName: Build & Upload Artifact
    pool:
      vmImage: windows-latest

    steps:
      - checkout: self

      - task: UseDotNet@2
        displayName: Setup .NET
        inputs:
          version: 10.0.x

      - script: dotnet restore
        displayName: Restore
        workingDirectory: HID-Test-App

      - script: >
          dotnet publish HID-Test-App/HID-Test-App.csproj
          -c Release
          -r win-x64
          --output "$(Build.SourcesDirectory)\publish"
        displayName: Publish
        workingDirectory: HID-Test-App

      - pwsh: |
          Rename-Item -Path "$(Build.SourcesDirectory)\publish\HID-Test-App.exe" `
                      -NewName "HID-Test-App-$(Build.SourceBranchName).exe"
        displayName: Rename artifact

      - task: PublishPipelineArtifact@1
        displayName: Upload artifact
        inputs:
          targetPath: $(Build.SourcesDirectory)\publish\HID-Test-App-$(Build.SourceBranchName).exe
          artifact: HID-Test-App-$(Build.SourceBranchName)
          publishLocation: pipeline
